blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/o2alexanderfedin/claude-legal-agents/security/advisories/new
    about: Report security vulnerabilities privately
  - name: Legal Questions
    url: https://github.com/o2alexanderfedin/claude-legal-agents/discussions
    about: For legal questions, consult a licensed attorney (not GitHub Issues)
